&lt;%@ page language=&quot;java&quot; contentType=&quot;text/html; charset=UTF-8&quot; pageEncoding=&quot;UTF-
8&quot;%&gt;
&lt;%@ page import=&quot;com.travel.model.User&quot; %&gt;
&lt;%@ page import=&quot;java.util.List&quot; %&gt;
&lt;%@ page import=&quot;com.travel.dao.PackageDAO&quot; %&gt;
&lt;%@ page import=&quot;com.travel.model.Package&quot; %&gt;
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;title&gt;Dashboard - Travel Management&lt;/title&gt;
&lt;link rel=&quot;stylesheet&quot; href=&quot;css/style.css&quot;&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;header&gt;
&lt;h1&gt;Welcome, ${user.fullName}&lt;/h1&gt;
&lt;a href=&quot;logout.jsp&quot;&gt;Logout&lt;/a&gt;
&lt;/header&gt;
&lt;nav&gt;
&lt;a href=&quot;dashboard.jsp&quot;&gt;Home&lt;/a&gt;
&lt;a href=&quot;packages.jsp&quot;&gt;Packages&lt;/a&gt;
&lt;a href=&quot;hotels.jsp&quot;&gt;Hotels&lt;/a&gt;
&lt;a href=&quot;my_bookings.jsp&quot;&gt;My Bookings&lt;/a&gt;
&lt;/nav&gt;
&lt;section class=&quot;packages-section&quot;&gt;

&lt;h2&gt;Available Travel Packages&lt;/h2&gt;
&lt;% PackageDAO packageDAO = new PackageDAO();
List&lt;Package&gt; packages = packageDAO.getAllPackages();
for (Package pkg : packages) { %&gt;
&lt;div class=&quot;package-card&quot;&gt;
&lt;h3&gt;${pkg.packageName}&lt;/h3&gt;
&lt;p&gt;�� ${pkg.destination}&lt;/p&gt;
&lt;p&gt;⏱️ ${pkg.durationDays} days&lt;/p&gt;
&lt;p&gt;�� ₹${pkg.price}&lt;/p&gt;
&lt;a href=&quot;booking.jsp?packageId=${pkg.packageId}&quot;&gt;Book Now&lt;/a&gt;
&lt;/div&gt;
&lt;% } %&gt;
&lt;/section&gt;
&lt;/body&gt;
&lt;/html&gt;